services:
  postgres:
    image: postgres:16-alpine3.18
    container_name: fullstack-teste-leek-postgres
    env_file:
      - ./api/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    command: -p ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: fullstack-teste-leek-api
    env_file:
      - ./api/.env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - network
    depends_on:
      - postgres

  front-end:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: fullstack-teste-leek-front-end
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
